package br.ufsc.Trabalho1.view;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import br.ufsc.Trabalho1.control.PersistanceCtrl;
import br.ufsc.Trabalho1.control.ScreenCtrl;
import br.ufsc.Trabalho1.model.Member;

public class ManageMemberScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewMemberScreen
     */
    public ManageMemberScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        detailsButton = new javax.swing.JButton();
        deleteMember = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        manageTrainingButton = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        
        ArrayList<Member> members = PersistanceCtrl.getInstance().getMemberList();
    	Member[] strings = new Member[members.size()];
    	for(int i = 0; i < members.size(); i++) {
    		strings[i] = members.get(i);
    	}
        jList1.setModel(new javax.swing.AbstractListModel<Member>() {
            
            public int getSize() { return strings.length; }
            public Member getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        detailsButton.setText("Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        deleteMember.setText("Delete Member");
        deleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemberActionPerformed(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        manageTrainingButton.setText("Manage Training");
        manageTrainingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTrainingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageTrainingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(detailsButton)
                        .addGap(34, 34, 34)
                        .addComponent(manageTrainingButton)
                        .addGap(41, 41, 41)
                        .addComponent(deleteMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


	
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
    	setVisible(false);
    	ScreenCtrl.getInstance().showMemberScreen();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void deleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemberActionPerformed
    	PersistanceCtrl.getInstance().remove(jList1.getSelectedValue());
    	updateData();
    }//GEN-LAST:event_deleteMemberActionPerformed

    private void manageTrainingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTrainingButtonActionPerformed
    	try {
    		ScreenCtrl.getInstance().showTrainingScreen(jList1.getSelectedValue());
    	}catch(NullPointerException e) {
    		JOptionPane.showMessageDialog(null, "No Member Selected.", "Attention", 1);
    	}
    }//GEN-LAST:event_manageTrainingButtonActionPerformed
    private void detailsButtonActionPerformed(ActionEvent evt) {
    	try {
	    	class DetailsPanel extends javax.swing.JFrame {
	
	    	    
	    	    public DetailsPanel() {
	    	        initComponents();
	    	    }
	
	    	    /**
	    	     * This method is called from within the constructor to initialize the form.
	    	     * WARNING: Do NOT modify this code. The content of this method is always
	    	     * regenerated by the Form Editor.
	    	     */
	    	    @SuppressWarnings("unchecked")
	    	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    	    private void initComponents() {
	
	    	        jPanel1 = new javax.swing.JPanel();
	    	        jLabel1 = new javax.swing.JLabel();
	    	        jLabel2 = new javax.swing.JLabel();
	    	        jLabel3 = new javax.swing.JLabel();
	    	        jLabel4 = new javax.swing.JLabel();
	    	        jLabel5 = new javax.swing.JLabel();
	    	        jLabel6 = new javax.swing.JLabel();
	    	        okButton = new javax.swing.JButton();
	
	    	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	
	    	        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
	
	    	        jLabel1.setText("Employee's Name:     " + jList1.getSelectedValue().getName());
	
	    	        jLabel3.setText("Employee's RG:     " + jList1.getSelectedValue().getRg());
	
	    	        jLabel4.setText("Employee's Address:     " + jList1.getSelectedValue().getAddress());
	
	    	        jLabel5.setText("Employee's Phone:     " + jList1.getSelectedValue().getPhone());
	
	    	        jLabel6.setText("Employee's Birthday:     " + jList1.getSelectedValue().getBirthday());
	
	    	        jLabel2.setText("Employee's CPF:     " + jList1.getSelectedValue().getCpf());
	
	    	        okButton.setText("OK");
	    	        okButton.addActionListener(new java.awt.event.ActionListener() {
	    	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	    	                okButtonActionPerformed(evt);
	    	            }
	    	        });
	
	    	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	    	        jPanel1.setLayout(jPanel1Layout);
	    	        jPanel1Layout.setHorizontalGroup(
	    	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    	            .addGroup(jPanel1Layout.createSequentialGroup()
	    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    	                    .addGroup(jPanel1Layout.createSequentialGroup()
	    	                        .addGap(35, 35, 35)
	    	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	    	                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	    	                        .addGap(92, 92, 92)
	    	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	    	                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	    	                    .addGroup(jPanel1Layout.createSequentialGroup()
	    	                        .addGap(106, 106, 106)
	    	                        .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                        .addGap(42, 42, 42)))
	    	                .addGap(92, 92, 92))
	    	        );
	    	        jPanel1Layout.setVerticalGroup(
	    	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    	            .addGroup(jPanel1Layout.createSequentialGroup()
	    	                .addGap(23, 23, 23)
	    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	    	                    .addComponent(jLabel1)
	    	                    .addComponent(jLabel4))
	    	                .addGap(18, 18, 18)
	    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	    	                    .addComponent(jLabel2)
	    	                    .addComponent(jLabel5))
	    	                .addGap(18, 18, 18)
	    	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	    	                    .addComponent(jLabel3)
	    	                    .addComponent(jLabel6))
	    	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
	    	                .addComponent(okButton))
	    	        );
	
	    	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	    	        getContentPane().setLayout(layout);
	    	        layout.setHorizontalGroup(
	    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    	            .addGroup(layout.createSequentialGroup()
	    	                .addContainerGap()
	    	                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                .addContainerGap())
	    	        );
	    	        layout.setVerticalGroup(
	    	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    	            .addGroup(layout.createSequentialGroup()
	    	                .addContainerGap()
	    	                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	    	                .addContainerGap())
	    	        );
	
	    	        pack();
	    	    }// </editor-fold>                        
	
	    	    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
	    	        setVisible(false);
	    	    }                                        
	
	    	    /**
	    	     * @param args the command line arguments
	    	     */
	
	    	    // Variables declaration - do not modify                     
	    	    private javax.swing.JLabel jLabel1;
	    	    private javax.swing.JLabel jLabel2;
	    	    private javax.swing.JLabel jLabel3;
	    	    private javax.swing.JLabel jLabel4;
	    	    private javax.swing.JLabel jLabel5;
	    	    private javax.swing.JLabel jLabel6;
	    	    private javax.swing.JPanel jPanel1;
	    	    private javax.swing.JButton okButton;
	    	    // End of variables declaration                   
	    	}
	    	DetailsPanel details = new DetailsPanel();
	    	details.setVisible(true);
    	}catch(NullPointerException e) {
    		JOptionPane.showMessageDialog(null, "No Member Selected.", "Attention", 1);
    	}

	
	}
    

//s
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteMember;
    private javax.swing.JButton detailsButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JList<Member> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageTrainingButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
	public void updateData() {
		ArrayList<Member> members = PersistanceCtrl.getInstance().getMemberList();
    	Member[] strings = new Member[members.size()];
    	for(int i = 0; i < members.size(); i++) {
    		strings[i] = members.get(i);
    	}
        jList1.setModel(new javax.swing.AbstractListModel<Member>() {
            
            public int getSize() { return strings.length; }
            public Member getElementAt(int i) { return strings[i]; }
        });
        this.repaint();
		
	}
}
